### ISSUE TITLE
Truncated commit messages can lead to incorrect URLs

### ISSUE THREAD

**Issue by ddgenome** [atomist/handlers#3]
We truncate commit messages at 50 characters. If a recognizable URL begins appears before the truncation, Slack automatically converts it into an incorrect link.

Examples:
https://atomist-community.slack.com/archives/rug/p1486093228002444
https://atomist-community.slack.com/files/jb/F4185L0ET/pasted_image_at_2017_02_03_11_45_am.png

/cc @janekdb

**Comment by tanya-coding** [comment]
This is a bug in our slack message rendering in bot - I'll create an issue there and will update this one when we fix it.
